package de.slisson.mps.editor.multiline.behavior;

/*Generated by MPS */

import jetbrains.mps.smodel.SNode;
import jetbrains.mps.lang.editor.behavior.EditorCellModel_Behavior;

public class CellModel_Multiline_Behavior {
  public static void init(SNode thisNode) {
  }

  public static String virtual_getClosingText_1220339738643(SNode thisNode) {
    return EditorCellModel_Behavior.callSuper_getClosingText_1220339738643(thisNode, "de.slisson.mps.editor.multiline.structure.CellModel_Multiline") + "\\n";
  }
}
