package de.slisson.mps.editor.multiline.behavior;

/*Generated by MPS */

import jetbrains.mps.lang.editor.behavior.CellModel_Property_BehaviorDescriptor;
import jetbrains.mps.smodel.SNode;

public class CellModel_Multiline_BehaviorDescriptor extends CellModel_Property_BehaviorDescriptor {
  public CellModel_Multiline_BehaviorDescriptor() {
  }

  public String virtual_getClosingText_1220339738643(SNode thisNode) {
    return CellModel_Multiline_Behavior.virtual_getClosingText_1220339738643(thisNode);
  }

  @Override
  public String getConceptFqName() {
    return "de.slisson.mps.editor.multiline.structure.CellModel_Multiline";
  }
}
