package de.slisson.mps.editor.multiline.demolang.editor;

/*Generated by MPS */

import jetbrains.mps.nodeEditor.cells.EditorCell;
import jetbrains.mps.smodel.SNode;
import jetbrains.mps.nodeEditor.EditorContext;
import jetbrains.mps.nodeEditor.CellActionType;
import jetbrains.mps.nodeEditor.EditorCellAction;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SPropertyOperations;

public class am {
  public static void setCellActions(EditorCell editorCell, SNode node, EditorContext context) {
    editorCell.setAction(CellActionType.DELETE_TO_WORD_END, new am.am_DELETE_TO_WORD_END(node));
  }

  public static class am_DELETE_TO_WORD_END extends EditorCellAction {
    /*package*/ SNode myNode;

    public am_DELETE_TO_WORD_END(SNode node) {
      this.myNode = node;
    }

    public void execute(EditorContext editorContext) {
      this.execute_internal(editorContext, this.myNode);
    }

    public void execute_internal(EditorContext editorContext, SNode node) {
      SPropertyOperations.set(node, "text", SPropertyOperations.getString(node, "text"));
    }
  }
}
