package de.slisson.mps.editor.multiline.runtime.plugin;

/*Generated by MPS */

import jetbrains.mps.plugins.actions.BaseKeymapChanges;
import com.intellij.openapi.actionSystem.Shortcut;
import com.intellij.openapi.actionSystem.KeyboardShortcut;
import javax.swing.KeyStroke;

public class Default_KeymapChanges extends BaseKeymapChanges {
  public Default_KeymapChanges() {
    // simple 
    addSimpleShortcut("de.slisson.mps.editor.multiline.runtime.plugin.SelectWordLeft_Action", getShortcut("shift LEFT"));
    addSimpleShortcut("de.slisson.mps.editor.multiline.runtime.plugin.SelectWordRight_Action", getShortcut("shift RIGHT"));
    addSimpleShortcut("de.slisson.mps.editor.multiline.runtime.plugin.SelectWordUp_Action", getShortcut("shift UP"));
    // simple parameterized 
    // complex 
  }

  public String getScheme() {
    return "$default";
  }

  public static Shortcut getShortcut(String stroke) {
    return new KeyboardShortcut(KeyStroke.getKeyStroke(stroke), null);
  }
}
