package de.slisson.mps.editor.multiline.demolang.behavior;

/*Generated by MPS */

import jetbrains.mps.lang.core.behavior.BaseConcept_BehaviorDescriptor;

public class ConceptA_BehaviorDescriptor extends BaseConcept_BehaviorDescriptor {
  public ConceptA_BehaviorDescriptor() {
  }

  @Override
  public String getConceptFqName() {
    return "de.slisson.mps.editor.multiline.demolang.structure.ConceptA";
  }
}
