package de.slisson.mps.editor.multiline.cells;

/*Generated by MPS */

import jetbrains.mps.nodeEditor.EditorCellAction;
import jetbrains.mps.nodeEditor.EditorContext;

public class NewLineAction extends EditorCellAction {
  private EditorCell_Word myWordCell;

  public NewLineAction(EditorCell_Word wordCell) {
    this.myWordCell = wordCell;
  }

  public void execute(EditorContext context) {
    myWordCell.insertText("\n");
  }
}
