package de.slisson.mps.editor.multiline.cells;

/*Generated by MPS */

import jetbrains.mps.nodeEditor.EditorCellAction;
import jetbrains.mps.nodeEditor.EditorContext;
import jetbrains.mps.nodeEditor.selection.SelectionManager;
import jetbrains.mps.internal.collections.runtime.Sequence;

public class SelectLeftRightAction extends EditorCellAction {
  private boolean myLeft;
  private EditorCell_Word myWordCell;

  public SelectLeftRightAction(boolean left, EditorCell_Word wordCell) {
    myLeft = left;
    myWordCell = wordCell;
  }

  public void execute(EditorContext context) {
    int newPosition = (myLeft ?
      myWordCell.getCaretPosition() - 1 :
      myWordCell.getCaretPosition() + 1
    );
    if (myWordCell.isCaretPositionAllowed(newPosition)) {
      myWordCell.setCaretPosition(newPosition, true);
      context.getNodeEditorComponent().resetLastCaretX();
      myWordCell.ensureCaretVisible();
      return;
    }

    SelectionManager selectionManager = context.getNodeEditorComponent().getSelectionManager();
    EditorCell_Multiline parent = myWordCell.getParent();
    int index = Sequence.fromIterable(parent.getWordCells()).indexOf(myWordCell);
    int wordStart = myWordCell.getParent().getTextBefore(myWordCell, 0).length();
    int selectionStart = ((myLeft ?
      myWordCell.getSelectionEnd() :
      myWordCell.getSelectionStart()
    )) + wordStart;
    int selectionEnd = ((myLeft ?
      myWordCell.getSelectionStart() - 1 :
      myWordCell.getSelectionEnd() + 1
    )) + wordStart;
    selectionManager.pushSelection(new MultilineSelection(myWordCell.getEditor(), parent, selectionStart, selectionEnd));
  }
}
