package de.slisson.mps.editor.multiline.cells;

/*Generated by MPS */

import jetbrains.mps.nodeEditor.EditorCellAction;
import jetbrains.mps.nodeEditor.EditorContext;
import jetbrains.mps.nodeEditor.cells.EditorCell;
import jetbrains.mps.nodeEditor.cells.CellConditions;
import jetbrains.mps.nodeEditor.selection.SelectionManager;

public class SelectUpDownAction extends EditorCellAction {
  private EditorCell_Word myWordCell;
  private boolean myUp;

  public SelectUpDownAction(EditorCell_Word wordCell, boolean up) {
    this.myWordCell = wordCell;
    myUp = up;
  }

  public void execute(EditorContext context) {
    EditorCell upperOrLower = (myUp ?
      myWordCell.getUpper(CellConditions.SELECTABLE, myWordCell.getCaretX()) :
      myWordCell.getLower(CellConditions.SELECTABLE, myWordCell.getCaretX())
    );
    if (!(upperOrLower instanceof EditorCell_Word)) {
      return;
    }
    EditorCell_Word upperOrLowerWordCell = (EditorCell_Word) upperOrLower;
    if (upperOrLowerWordCell.getParent() != myWordCell.getParent()) {
      return;
    }

    EditorCell_Multiline parent = myWordCell.getParent();

    int selStart = parent.getTextBefore(myWordCell, myWordCell.getCaretPosition()).length();
    upperOrLowerWordCell.setCaretX(myWordCell.getCaretX());
    int selEnd = parent.getTextBefore(upperOrLowerWordCell, upperOrLowerWordCell.getCaretPosition()).length();

    SelectionManager selectionManager = context.getNodeEditorComponent().getSelectionManager();
    selectionManager.pushSelection(new MultilineSelection(myWordCell.getEditor(), parent, selStart, selEnd));

  }
}
