package de.slisson.mps.editor.multiline.cells;

/*Generated by MPS */

import jetbrains.mps.nodeEditor.EditorCellKeyMapAction;
import jetbrains.mps.logging.Logger;
import java.awt.event.KeyEvent;
import jetbrains.mps.nodeEditor.EditorContext;

public class TabAction extends EditorCellKeyMapAction {
  private static final Logger LOG = Logger.getLogger(TabAction.class);

  private EditorCell_Word myWordCell;

  public TabAction(EditorCell_Word wordCell) {
    this.myWordCell = wordCell;
  }

  public void execute(KeyEvent event, EditorContext context) {
    myWordCell.insertText("  ");
  }
}
