package de.slisson.mps.editor.multiline.cells;

/*Generated by MPS */

import jetbrains.mps.nodeEditor.EditorCellAction;
import jetbrains.mps.nodeEditor.EditorContext;
import de.slisson.mps.editor.multiline.runtime.ClipboardUtils;

public class WordPasteAction extends EditorCellAction {
  private EditorCell_Word myWordCell;

  public WordPasteAction(EditorCell_Word wordCell) {
    myWordCell = wordCell;
  }

  public void execute(EditorContext context) {
    myWordCell.insertText(ClipboardUtils.getClipboardText());
  }
}
