package de.slisson.mps.editor.multiline.runtime;

/*Generated by MPS */

import java.awt.datatransfer.Transferable;
import com.intellij.ide.CopyPasteManagerEx;
import java.awt.datatransfer.DataFlavor;
import java.awt.datatransfer.UnsupportedFlavorException;
import java.io.IOException;

public class ClipboardUtils {
  public ClipboardUtils() {
  }

  public static String getClipboardText() {
    String result = "";
    for (Transferable content : CopyPasteManagerEx.getInstanceEx().getAllContents()) {
      if (content.isDataFlavorSupported(DataFlavor.stringFlavor)) {
        try {
          result = (String) content.getTransferData(DataFlavor.stringFlavor);
          break;
        } catch (UnsupportedFlavorException ex) {
        } catch (IOException ex) {
        }
      }
    }
    return result;
  }
}
