package de.slisson.mps.editor.multiline.cellProviders;

/*Generated by MPS */

import jetbrains.mps.nodeEditor.cellProviders.CellProviderWithRole;
import jetbrains.mps.logging.Logger;
import java.util.concurrent.atomic.AtomicLong;
import jetbrains.mps.smodel.SNode;
import jetbrains.mps.nodeEditor.EditorContext;
import jetbrains.mps.util.InternUtil;
import jetbrains.mps.smodel.SNodeOperations;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.AttributeOperations;
import jetbrains.mps.nodeEditor.attribute.AttributeKind;
import jetbrains.mps.nodeEditor.cellMenu.NodeSubstituteInfo;
import jetbrains.mps.nodeEditor.cells.EditorCell;
import jetbrains.mps.nodeEditor.cells.PropertyAccessor;
import de.slisson.mps.editor.multiline.cells.EditorCell_Multiline;

public class MultilineCellProvider extends CellProviderWithRole {
  private static final Logger LOG = Logger.getLogger(MultilineCellProvider.class);
  private static AtomicLong CALL_ID_SEQUENCE = new AtomicLong();

  private String myPropertyName;
  private SNode myPropertyDeclaration;

  public MultilineCellProvider(SNode node, EditorContext editorContext) {
    super(node, editorContext);
  }

  public void setRole(Object object) {
    myPropertyName = InternUtil.intern(String.valueOf(object));
    myPropertyDeclaration = getSNode().getPropertyDeclaration(myPropertyName);
    if (myPropertyDeclaration == null) {
      if (!(SNodeOperations.isUnknown(getSNode()))) {
        LOG.error("no property declaration could be found in NODE " + getSNode() + " for PROPERTY name " + myPropertyName);
      }
    }
  }

  public SNode getRoleAttribute() {
    SNode node = getSNode();
    return AttributeOperations.getPropertyAttribute(node, null, myPropertyName);
  }

  public Class getRoleAttributeClass() {
    return AttributeKind.Property.class;
  }

  public NodeSubstituteInfo createDefaultSubstituteInfo() {
    return null;
  }

  public EditorCell createEditorCell(EditorContext context) {
    PropertyAccessor propertyAccessor = new PropertyAccessor(getSNode(), myPropertyName, myReadOnly, myAllowsEmptyTarget, context);
    EditorCell editorCell = EditorCell_Multiline.create(context, propertyAccessor, getSNode());
    return editorCell;
  }
}
